#!/bin/bash

# Bundler Commands
alias b="bundle"
alias bi="b install --path vendor"
alias bx="bundle exec"
alias bl="bundle list"
alias bu="bundle update"
alias bp="bundle package"
alias binit="bi && bp && echo 'vendor/ruby' >> .gitignore"

alias dbscrub="bundle exec rake db:drop db:setup db:test:prepare"

bundler-help () {
  echo "Bundler Aliases Usage"
  echo
  echo " b     = bundle"
  echo " bi    = bundle install --path vendor"
  echo " bx    = bundle exec"
  echo " bl    = bundle list"
  echo " bu    = bundle update"
  echo " bp    = bundle package"
  echo " binit = bi && bp && echo 'vendor/ruby' >> .gitignore"
  echo
}

# Sublime
alias s='subl .'

# Heroku

alias h="heroku"
alias hr="heroku run"
alias hl="heroku logs"
